# Generated by Django 3.0.8 on 2024-02-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_decription',
            new_name='receipe_description',
        ),
    ]
