# Generated by Django 3.0.8 on 2024-02-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vega', '0003_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
